### ISSUE TITLE
Create Documentation 

### ISSUE THREAD

**Issue by bb7555** [rockerest/ribcage#1]
Do you mind if I start looking at writing up some documentation for this?

**Comment by rockerest** [comment]
I don't mind at all. I'd prefer if the documentation is contained in the README.md file (a la [Cookies](https://github.com/ScottHamper/Cookies)). I think it won't be large enough to merit it's own folder / website, and the README will be a good place to maintain it.

**Comment by bb7555** [comment]
great. we will probably want it moving forward anyway, if others need to work with ribcage moving forward. I'll start writing and open a pull request when i have a first draft and tag it to this issue

**Comment by rockerest** [comment]
Closed by 4b1f994f6f131c99d55c13914a26c7078b0d2411
